-- =============================================================================
-- 11_features.sql
-- Feature Dictionary for v1.0 of the FluidMind feature foundation.
-- =============================================================================

INSERT INTO feature_definitions (feature_set_version, feature_name, feature_group, data_type, scope, description, formula_text, unit, inputs, display_order) VALUES

  -- ============== STRUCTURE ==============
  ('v1.0', 'num_items',           'structure', 'numeric', 'formula_version',
   'Total number of formula_items in the version', 'count(formula_items)', 'count',
   '{"tables":["formula_items"]}'::jsonb, 10),
  ('v1.0', 'num_phases',          'structure', 'numeric', 'formula_version',
   'Distinct process phases (A/B/C/...) used', 'count(distinct phase)', 'count',
   '{"tables":["formula_items"]}'::jsonb, 11),
  ('v1.0', 'num_steps',           'structure', 'numeric', 'formula_version',
   'Distinct process steps used', 'count(distinct step_no)', 'count',
   '{"tables":["formula_items"]}'::jsonb, 12),
  ('v1.0', 'num_active',          'structure', 'numeric', 'formula_version',
   'Items where role = "active" or "antiwear"', NULL, 'count',
   '{"tables":["formula_items"]}'::jsonb, 13),
  ('v1.0', 'num_base',            'structure', 'numeric', 'formula_version',
   'Items where role = "base"', NULL, 'count',
   '{"tables":["formula_items"]}'::jsonb, 14),
  ('v1.0', 'num_additive',        'structure', 'numeric', 'formula_version',
   'Items where role is in (antiwear,antioxidant,vi_improver,detergent,...)', NULL, 'count',
   '{"tables":["formula_items"]}'::jsonb, 15),
  ('v1.0', 'pct_active',          'structure', 'numeric', 'formula_version',
   'Sum of percentages where role implies active function', 'Σ percentage', '%',
   '{"tables":["formula_items"]}'::jsonb, 16),
  ('v1.0', 'pct_base',            'structure', 'numeric', 'formula_version',
   'Sum of base-oil percentages', NULL, '%',
   '{"tables":["formula_items"]}'::jsonb, 17),
  ('v1.0', 'critical_count',      'structure', 'numeric', 'formula_version',
   'Items marked is_critical = true', 'count(is_critical)', 'count',
   '{"tables":["formula_items"]}'::jsonb, 18),
  ('v1.0', 'optional_count',      'structure', 'numeric', 'formula_version',
   'Items marked is_optional = true', 'count(is_optional)', 'count',
   '{"tables":["formula_items"]}'::jsonb, 19),

  -- ============== WEIGHTED PROPERTY ==============
  ('v1.0', 'weighted_density',    'weighted_property', 'numeric', 'formula_version',
   'Mass-weighted average density of resolved materials',
   'Σ pct_i × density_i / Σ pct_i (with density)', 'g/cm³',
   '{"tables":["formula_items","raw_materials"],"columns":["raw_materials.density"]}'::jsonb, 20),
  ('v1.0', 'weighted_molecular_weight', 'weighted_property', 'numeric', 'formula_version',
   'Mass-weighted average molecular weight', NULL, 'g/mol',
   '{"tables":["formula_items","raw_materials"],"columns":["raw_materials.molecular_weight"]}'::jsonb, 21),
  ('v1.0', 'weighted_flash_point', 'weighted_property', 'numeric', 'formula_version',
   'Mass-weighted average flash point', NULL, '°C',
   '{"tables":["formula_items","raw_materials"],"columns":["raw_materials.flash_point_c"]}'::jsonb, 22),
  ('v1.0', 'weighted_ph',          'weighted_property', 'numeric', 'formula_version',
   'Mass-weighted average pH', NULL, NULL,
   '{"tables":["formula_items","raw_materials"],"columns":["raw_materials.ph_value"]}'::jsonb, 23),

  -- ============== LOG-MIX (RHEOLOGY) ==============
  ('v1.0', 'weighted_viscosity_log', 'log_mix', 'numeric', 'formula_version',
   'Naive log-weighted average of ln(viscosity_cst) — simpler than Refutas',
   'Σ pct_i × ln(ν_i) / Σ pct_i', 'ln(cSt)',
   '{"tables":["formula_items","raw_materials"]}'::jsonb, 30),
  ('v1.0', 'blended_viscosity_cst', 'log_mix', 'numeric', 'formula_version',
   'Refutas-equation-blended kinematic viscosity at 100°C',
   'VBN_i = 14.534 × ln(ln(ν_i + 0.8)) + 10.975 ; VBN_blend = Σ x_i × VBN_i ; ν_blend = exp(exp((VBN_blend − 10.975)/14.534)) − 0.8',
   'cSt',
   '{"tables":["formula_items","raw_materials"]}'::jsonb, 31),

  -- ============== COMPLEXITY ==============
  ('v1.0', 'complexity_entropy',     'complexity', 'numeric', 'formula_version',
   'Shannon entropy of normalized item percentages',
   '−Σ p_i × ln(p_i)  where p_i = pct_i/100',  'nats',
   '{"tables":["formula_items"]}'::jsonb, 40),
  ('v1.0', 'simpson_diversity',     'complexity', 'numeric', 'formula_version',
   'Simpson''s diversity (1 − Σ p_i²)', NULL, 'unitless',
   '{"tables":["formula_items"]}'::jsonb, 41),
  ('v1.0', 'concentration_top3',    'complexity', 'numeric', 'formula_version',
   'Sum of the three largest percentages', NULL, '%',
   '{"tables":["formula_items"]}'::jsonb, 42),
  ('v1.0', 'effective_n_ingredients','complexity', 'numeric', 'formula_version',
   'exp(entropy) — effective number of equally-significant ingredients',
   'exp(−Σ p_i × ln(p_i))', 'count',
   '{"tables":["formula_items"]}'::jsonb, 43),

  -- ============== COST ==============
  ('v1.0', 'total_cost',            'cost', 'numeric', 'formula_version',
   'Total formulation cost per batch_size unit',
   'Σ amount_i × unit_cost_i', 'currency',
   '{"tables":["formula_items","raw_materials"]}'::jsonb, 50),
  ('v1.0', 'cost_per_kg',           'cost', 'numeric', 'formula_version',
   'Cost normalized by batch size', 'total_cost / batch_size', 'currency/kg',
   '{"tables":["formula_versions","formula_items","raw_materials"]}'::jsonb, 51),
  ('v1.0', 'top_cost_share',        'cost', 'numeric', 'formula_version',
   'max(item_cost) / total_cost — concentration of cost in a single ingredient',
   NULL, 'unitless',
   '{"tables":["formula_items","raw_materials"]}'::jsonb, 52),

  -- ============== FUNCTIONAL ==============
  ('v1.0', 'has_zddp',              'functional', 'boolean', 'formula_version',
   'Whether any item resolves to a ZDDP (anti-wear) material',
   'any(material.code matches ZDDP|RM-ZDDP-* or alias)', 'bool',
   '{"tables":["formula_items","raw_materials","raw_material_aliases"]}'::jsonb, 60),
  ('v1.0', 'has_pao',               'functional', 'boolean', 'formula_version',
   'Whether any base oil is a PAO (synthetic) base', NULL, 'bool',
   '{"tables":["formula_items","raw_materials"]}'::jsonb, 61),
  ('v1.0', 'has_vi_improver',       'functional', 'boolean', 'formula_version',
   'Whether any item is a VI improver', NULL, 'bool',
   '{"tables":["formula_items","raw_materials"]}'::jsonb, 62),
  ('v1.0', 'has_antioxidant',       'functional', 'boolean', 'formula_version',
   'Whether any item is an antioxidant', NULL, 'bool',
   '{"tables":["formula_items","raw_materials"]}'::jsonb, 63),
  ('v1.0', 'additive_to_base_ratio','functional', 'numeric', 'formula_version',
   'Σ additive percentages / Σ base-oil percentages',
   'pct_additive / pct_base', 'unitless',
   '{"tables":["formula_items"]}'::jsonb, 64),
  ('v1.0', 'phosphorus_ppm_estimate','functional', 'numeric', 'formula_version',
   'Estimated phosphorus contribution from ZDDP × P content × pct',
   'Σ pct_i × P_pct_i × 1e4', 'ppm',
   '{"tables":["formula_items","raw_materials"],"columns":["raw_materials.properties.phosphorus_pct"]}'::jsonb, 65)

ON CONFLICT (feature_set_version, feature_name) DO NOTHING;
